cmake -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DACTIVE_REGION="LORAMAC_REGION_CN470" -DSUB_PROJECT="classA"  -DREGION_CN470="ON" -DREGION_EU868="OFF" -DBOARD="NucleoL073" -DMBED_RADIO_SHIELD="SX1276MB1MAS" ..

